23115129_Sathvik Reddy Duddela Assignment 1
dsgiitr/dsg-lecture-assignments pull request #2
Opened 2024-05-10 17:34 UTC by r4iden-IITR

2024-05-18 13:33 UTC, star-gazer111 requested changes
Q2 & 6 are wrong

2024-05-18 13:41 UTC, r4iden-IITR commented
> Q2 & 6 are wrong

sir could you please explain what i did wrong in both i'm not able to get

2024-05-18 13:50 UTC, r4iden-IITR commented
i got my mistake in 2nd but can you explain 6th and also 7th

2024-05-19 06:38 UTC, kartyg23 commented
you can refer to solutions of other students for doubt clarification.

2025-10-22 18:21 UTC, closed without merging